### ISSUE TITLE
TLS failing

### ISSUE THREAD

**Issue by hammy7867** [1Password/connect#38] opened 2022-06-14 20:32 UTC
I am running the connect containers in AWS Fargate. I am putting the certificate and key on a shared volume. I have verified that the certificate is valid, but am getting an error on the connect-api container startup

```Error: Server: (failed to setupServer), Wrapped: (TLS configuration), load certificate+key: tls: failed to find any PEM data in certificate input```

Any guidance on resolving the issue is appreciated.

**Comment by jpcoenen** [comment] 2022-06-16 12:16
Hey! 

I have not seen this error before, but some users on StackOverflow [suggest](https://stackoverflow.com/questions/57596920/failed-to-find-any-pem-data-in-key) it can be caused by:
- The key of certificate not being in PEM format (starting with `-----BEGIN CERTIFICATE-----` and `-----BEGIN [TYPE] PRIVATE KEY-----`)
- Some unexpected characters in either the certificate or the private keys, for example:
     - A byte-order-marking byte at the start
     - A mix of `\r\n` and `\n` as newlines.

In case of the latter, the tool [`dos2unix`](https://waterlan.home.xs4all.nl/dos2unix.html) can probably help you out (scroll down to "Ready-to-run binaries" or "Distributions including this version of dos2unix" to download/install). Just run `dos2unix <filename>` to convert it to a plain UTF8 file.

Let me know if that helps.

Joris

**Comment by jpcoenen** [comment] 2022-09-29 08:18
I'm closing this issue for now. Feel free to re-open if the problem still exists.

**Closed by jpcoenen** 2022-09-29 08:18 UTC
Labels: tracked
