### ISSUE TITLE
Resource usage explanation

### ISSUE THREAD

**Issue by tomjohnburton** [1Password/connect#46] opened 2022-08-09 16:44 UTC
I've been tracking the metrics of onepassword connect server deployed in a k8s environment. I wanted to understand why the usage pattern follows this gradual growth.

**CPU / Memory**
The dots represent container restarts.

<img width="1349" alt="Screenshot 2022-08-09 at 17 44 10" src="https://user-images.githubusercontent.com/39559415/183709605-a37ed4cc-c157-41d0-9e58-0848a3a92da8.png">

**Comment by ag-adampike** [comment] 2022-09-29 12:22
Hey @tomjohnburton. I'm closing this issue as a duplicate of #23.

**Closed by ag-adampike** 2022-09-29 12:22 UTC
Labels: duplicate
